# Generated by Django 3.1.5 on 2021-06-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210602_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
