# Generated by Django 3.1.5 on 2021-06-04 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210603_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='arthur',
            new_name='author',
        ),
    ]
