# Generated by Django 3.2.4 on 2021-06-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Home', 'Home'), ('Electronics', 'Electronics'), ('Toy', 'Toy')], default='No Category', max_length=100),
        ),
    ]
